name: Deployment Cloud Run Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build docker image
        run: docker build -t gcr.io/strapidemo-288715/strapidemo-staging .

      - name: Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/strapidemo-288715/strapidemo-staging
          service: strapidemo-staging
          project: strapidemo-288715
          region: us-central1
          env: ${{ secrets.GCLOUD_ENV_VARS }}
          service key: ${{ secrets.GCLOUD_AUTH }}
